apiVersion: v1
kind: Service
metadata:
  name: drafttesting
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: drafttesting
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080